services:
  postgres:
    image: postgres:16
    container_name: fraud_db
    environment:
      POSTGRES_DB: fraud_detection
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_pass
    ports:
      - "5433:5432"
    volumes:
      - fraud_pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud_user -d fraud_detection"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  fraud_pgdata:
